CREATE TABLE ALUNOS(
ID_ALUNO INT IDENTITY NOT NULL,
NOME NVARCHAR(100) NOT NULL,
EMAIL NVARCHAR(30) NOT NULL,
SENHA NVARCHAR(40) NOT NULL,
RA NVARCHAR(30) NOT NULL,
CONSTRAINT ID_ALUNO_PK PRIMARY KEY(ID_ALUNO))

CREATE TABLE PROFESSOR(
ID_PROF INT IDENTITY NOT NULL,
NOME NVARCHAR(100) NOT NULL,
EMAIL NVARCHAR(30) NOT NULL,
SENHA NVARCHAR(40) NOT NULL,
RA NVARCHAR(30) NOT NULL,
CONSTRAINT ID_PROF_PK PRIMARY KEY(ID_PROF))

CREATE TABLE ADMINISTRADOR(
ID_ADMIN INT IDENTITY NOT NULL,
NOME NVARCHAR(100) NOT NULL,
EMAIL NVARCHAR(30) NOT NULL,
SENHA NVARCHAR(40) NOT NULL,
RA NVARCHAR(30) NOT NULL,
CONSTRAINT ID_ADMIN_PK PRIMARY KEY(ID_ADMIN))